import { COMPANY_NAME } from "@/lib/constants";
import {
  TRANSPORT_RULE_MARKER,
  TRANSPORT_RULE_NAME,
} from "@/lib/deploy/transport-rule";

/** Escape content for a PowerShell double-quoted here-string @" ... "@ */
export function escapePowerShellHereString(value: string): string {
  // Here-strings cannot contain the closing delimiter on its own line.
  // Also escape ` so PowerShell does not treat sequences as escapes when later expanded in some hosts.
  return value.replaceAll("`", "``").replaceAll('"@', '`"@');
}

export function buildTransportRulePowerShell(options: {
  disclaimerHtml: string;
  recipientCount: number;
  companyName?: string;
  generatedAt?: string;
}): string {
  const html = escapePowerShellHereString(options.disclaimerHtml);
  const company = options.companyName || COMPANY_NAME;
  const generatedAt = options.generatedAt || new Date().toISOString();

  return `# =============================================================================
# DPM Corporate Signature — Exchange Online transport rule
# Generated by DPM Email Signatures (A1)
# Company: ${company}
# Generated: ${generatedAt}
# Recipients prepared in app directory: ${options.recipientCount}
# Rule name: ${TRANSPORT_RULE_NAME}
# =============================================================================
#
# HOW TO RUN
# 1. Open PowerShell 7+ (or Windows PowerShell 5.1) as a DPM admin
# 2. Install-Module ExchangeOnlineManagement -Scope CurrentUser   # once
# 3. Connect-ExchangeOnline   # sign in with Exchange Admin / Global Admin
# 4. Run this script
#
# WHAT IT DOES
# - Creates or updates an outbound mail-flow rule
# - Appends HTML disclaimer/signature for messages leaving the organization
# - Skips messages that already contain the hidden marker (avoids reply stacking)
#
# LIMITATIONS
# - Signature is added after send (not visible while composing)
# - Personalization uses Exchange disclaimer macros (%%DisplayName%%, %%Title%%, …)
# - FindMi-perfect per-person HTML is in the separate JSON pack, not this single rule
# - Microsoft Graph cannot manage Outlook roaming signatures
#
# VERIFY
# Send a test message from a DPM mailbox to an external address and confirm the footer.
# =============================================================================

$ErrorActionPreference = "Stop"
$RuleName = "${TRANSPORT_RULE_NAME}"
$Marker = "${TRANSPORT_RULE_MARKER}"

$DisclaimerHtml = @"
${html}
"@

Write-Host "Connecting is required before this script runs commands."
Write-Host "If not connected: Connect-ExchangeOnline"
Write-Host ""

$existing = Get-TransportRule -Identity $RuleName -ErrorAction SilentlyContinue

if ($null -ne $existing) {
  Set-TransportRule -Identity $RuleName \`
    -ApplyHtmlDisclaimerText $DisclaimerHtml \`
    -ApplyHtmlDisclaimerLocation Append \`
    -ApplyHtmlDisclaimerFallbackAction Wrap \`
    -ExceptIfBodyContainsWords $Marker \`
    -FromScope InOrganization \`
    -SentToScope NotInOrganization \`
    -Mode Enforce

  Write-Host "Updated transport rule: $RuleName"
} else {
  New-TransportRule -Name $RuleName \`
    -FromScope InOrganization \`
    -SentToScope NotInOrganization \`
    -ApplyHtmlDisclaimerText $DisclaimerHtml \`
    -ApplyHtmlDisclaimerLocation Append \`
    -ApplyHtmlDisclaimerFallbackAction Wrap \`
    -ExceptIfBodyContainsWords $Marker \`
    -Mode Enforce

  Write-Host "Created transport rule: $RuleName"
}

Get-TransportRule -Identity $RuleName |
  Select-Object Name, State, Mode, FromScope, SentToScope, Priority |
  Format-List

Write-Host ""
Write-Host "Done. Send a test message outside the tenant to verify the signature."
`;
}
