import { COMPANY_NAME } from "@/lib/constants";
import {
  TRANSPORT_RULE_MARKER,
  TRANSPORT_RULE_NAME,
} from "@/lib/deploy/transport-rule";
import { normalizePublishEmails } from "@/lib/deploy/rule-scope";

/** Escape content for a PowerShell double-quoted here-string @" ... "@ */
export function escapePowerShellHereString(value: string): string {
  return value.replaceAll("`", "``").replaceAll('"@', '`"@');
}

function formatEmailArray(emails: string[]): string {
  if (!emails.length) return "@()";
  return (
    "@(\n" +
    emails.map((email) => `  '${email.replaceAll("'", "''")}'`).join("\n") +
    "\n)"
  );
}

export function buildTransportRulePowerShell(options: {
  disclaimerHtml: string;
  recipientCount: number;
  companyName?: string;
  generatedAt?: string;
  /** When set, rule applies only to these sender addresses. */
  fromEmails?: string[];
}): string {
  const html = escapePowerShellHereString(options.disclaimerHtml);
  const company = options.companyName || COMPANY_NAME;
  const generatedAt = options.generatedAt || new Date().toISOString();
  const fromEmails = normalizePublishEmails(options.fromEmails || []);
  const selected = fromEmails.length > 0;
  const audienceLabel = selected
    ? `Selected senders (${fromEmails.length})`
    : `All in-organization senders (directory prepared: ${options.recipientCount})`;

  const fromBlock = selected
    ? `
$FromAddresses = ${formatEmailArray(fromEmails)}
`
    : `
$FromAddresses = @()
`;

  const setParams = selected
    ? `Set-TransportRule -Identity $RuleName \`
    -ApplyHtmlDisclaimerText $DisclaimerHtml \`
    -ApplyHtmlDisclaimerLocation Append \`
    -ApplyHtmlDisclaimerFallbackAction Wrap \`
    -ExceptIfBodyContainsWords $Marker \`
    -From $FromAddresses \`
    -FromScope $null \`
    -SentToScope NotInOrganization \`
    -Mode Enforce`
    : `Set-TransportRule -Identity $RuleName \`
    -ApplyHtmlDisclaimerText $DisclaimerHtml \`
    -ApplyHtmlDisclaimerLocation Append \`
    -ApplyHtmlDisclaimerFallbackAction Wrap \`
    -ExceptIfBodyContainsWords $Marker \`
    -From $null \`
    -FromScope InOrganization \`
    -SentToScope NotInOrganization \`
    -Mode Enforce`;

  const newParams = selected
    ? `New-TransportRule -Name $RuleName \`
    -From $FromAddresses \`
    -SentToScope NotInOrganization \`
    -ApplyHtmlDisclaimerText $DisclaimerHtml \`
    -ApplyHtmlDisclaimerLocation Append \`
    -ApplyHtmlDisclaimerFallbackAction Wrap \`
    -ExceptIfBodyContainsWords $Marker \`
    -Mode Enforce`
    : `New-TransportRule -Name $RuleName \`
    -FromScope InOrganization \`
    -SentToScope NotInOrganization \`
    -ApplyHtmlDisclaimerText $DisclaimerHtml \`
    -ApplyHtmlDisclaimerLocation Append \`
    -ApplyHtmlDisclaimerFallbackAction Wrap \`
    -ExceptIfBodyContainsWords $Marker \`
    -Mode Enforce`;

  return `# =============================================================================
# DPM Corporate Signature — Exchange Online transport rule
# Generated by DPM Email Signatures (A1)
# Company: ${company}
# Generated: ${generatedAt}
# Audience: ${audienceLabel}
# Rule name: ${TRANSPORT_RULE_NAME}
# =============================================================================
#
# HOW TO RUN
# 1. Open PowerShell 7+ (or Windows PowerShell 5.1) as a DPM admin
# 2. Install-Module ExchangeOnlineManagement -Scope CurrentUser   # once
# 3. Connect-ExchangeOnline   # sign in with Exchange Admin / Global Admin
# 4. Run this script
#
# WHAT IT DOES
# - Creates or updates an outbound mail-flow rule
# - Appends HTML disclaimer/signature for messages leaving the organization
# - ${selected ? "Applies only to the selected sender mailbox(es)" : "Applies to all in-organization senders"}
# - Skips messages that already contain the hidden marker (avoids reply stacking)
#
# VERIFY
# Send a test message from a covered mailbox to an external address and confirm the footer.
# =============================================================================

$ErrorActionPreference = "Stop"
$RuleName = "${TRANSPORT_RULE_NAME}"
$Marker = "${TRANSPORT_RULE_MARKER}"
${fromBlock}
$DisclaimerHtml = @"
${html}
"@

Write-Host "Connecting is required before this script runs commands."
Write-Host "If not connected: Connect-ExchangeOnline"
Write-Host "Audience: ${audienceLabel}"
Write-Host ""

$existing = Get-TransportRule -Identity $RuleName -ErrorAction SilentlyContinue

if ($null -ne $existing) {
  ${setParams}

  Write-Host "Updated transport rule: $RuleName"
} else {
  ${newParams}

  Write-Host "Created transport rule: $RuleName"
}

Get-TransportRule -Identity $RuleName |
  Select-Object Name, State, Mode, FromScope, SentToScope, Priority, From |
  Format-List

Write-Host ""
Write-Host "Done. Send a test message outside the tenant to verify the signature."
`;
}
