import { DEFAULT_LOGO_PATH, DOSSANI_DISCLAIMER } from "./constants";
import type { AppState, Campaign, DirectoryUser, SignatureTemplate } from "./types";

export const DEMO_USERS: DirectoryUser[] = [
  {
    id: "u1",
    displayName: "Catherine Leman",
    email: "catherine.leman@dossaniparadise.com",
    jobTitle: "Property Manager",
    department: "Executive",
    phone: "(305) 555-0140",
    company: "Dossani Paradise Management",
    website: "https://www.dossaniparadise.com",
    streetAddress: "1200 Brickell Avenue, Suite 400",
    cityStateZip: "Miami, FL 33131",
    location: "Miami, FL",
    groups: ["Leadership"],
    signatureId: "t-dossani",
  },
  {
    id: "u2",
    displayName: "Daniel Brooks",
    email: "daniel.brooks@dossaniparadise.com",
    jobTitle: "Leasing Consultant",
    department: "Sales",
    phone: "(305) 555-0142",
    company: "Dossani Paradise Management",
    website: "https://www.dossaniparadise.com",
    streetAddress: "1200 Brickell Avenue, Suite 400",
    cityStateZip: "Miami, FL 33131",
    location: "Miami, FL",
    groups: ["Leasing"],
    signatureId: "t-dossani",
  },
  {
    id: "u3",
    displayName: "Maya Chen",
    email: "maya.chen@dossaniparadise.com",
    jobTitle: "Operations Coordinator",
    department: "Support",
    phone: "(305) 555-0148",
    company: "Dossani Paradise Management",
    website: "https://www.dossaniparadise.com",
    streetAddress: "890 Ocean Drive",
    cityStateZip: "Miami Beach, FL 33139",
    location: "Miami Beach, FL",
    groups: ["Operations"],
    signatureId: "t-dossani",
  },
  {
    id: "u4",
    displayName: "Jordan Blake",
    email: "jordan.blake@dossaniparadise.com",
    jobTitle: "Resident Services Lead",
    department: "Support",
    phone: "(786) 555-0190",
    company: "Dossani Paradise Management",
    website: "https://www.dossaniparadise.com",
    streetAddress: "455 Coral Way",
    cityStateZip: "Coral Gables, FL 33134",
    location: "Coral Gables, FL",
    groups: ["Resident Services"],
    signatureId: "t-dossani",
  },
  {
    id: "u5",
    displayName: "Priya Nair",
    email: "priya.nair@dossaniparadise.com",
    jobTitle: "Accounting Manager",
    department: "Finance",
    phone: "(305) 555-0155",
    company: "Dossani Paradise Management",
    website: "https://www.dossaniparadise.com",
    streetAddress: "1200 Brickell Avenue, Suite 400",
    cityStateZip: "Miami, FL 33131",
    location: "Miami, FL",
    groups: ["Finance"],
    signatureId: "t-dossani",
  },
  {
    id: "u6",
    displayName: "Sam Ortiz",
    email: "sam.ortiz@dossaniparadise.com",
    jobTitle: "Human Resources",
    department: "HR",
    phone: "(305) 555-0160",
    company: "Dossani Paradise Management",
    website: "https://www.dossaniparadise.com",
    streetAddress: "1200 Brickell Avenue, Suite 400",
    cityStateZip: "Miami, FL 33131",
    location: "Miami, FL",
    groups: ["HR"],
    signatureId: "t-dossani",
  },
];

export const DEMO_TEMPLATES: SignatureTemplate[] = [
  {
    id: "t-dossani",
    name: "Dossani Paradise Corporate",
    description:
      "Company-wide signature with logo, FindMi-style address fields, and legal disclaimer.",
    layout: "corporate",
    primaryColor: "#1F4E79",
    accentColor: "#C0392B",
    fontFamily: "Georgia, 'Times New Roman', Times, serif",
    showPhoto: false,
    showLogo: true,
    showSocial: false,
    showThankYou: true,
    logoUrl: DEFAULT_LOGO_PATH,
    logoAlt: "Dossani Paradise Management",
    logoWidth: 56,
    companyNameLine1: "DOSSANI PARADISE",
    companyNameLine2: "MANAGEMENT",
    companyNameLine2Color: "#C0392B",
    ctaLabel: "",
    ctaUrl: "",
    websiteDisplay: "www.DossaniParadise.com",
    disclaimer: DOSSANI_DISCLAIMER,
    assignedDepartments: ["All"],
    assignedGroups: [],
    assignedUserIds: [],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t2",
    name: "Sales Modern",
    description: "Alternate layout for leasing / sales outreach.",
    layout: "modern",
    primaryColor: "#1F4E79",
    accentColor: "#C0392B",
    fontFamily: "Calibri, Arial, sans-serif",
    showPhoto: true,
    showLogo: true,
    showSocial: false,
    showThankYou: false,
    logoUrl: DEFAULT_LOGO_PATH,
    logoAlt: "Dossani Paradise Management",
    logoWidth: 48,
    companyNameLine1: "DOSSANI PARADISE",
    companyNameLine2: "MANAGEMENT",
    companyNameLine2Color: "#C0392B",
    ctaLabel: "Schedule a tour",
    ctaUrl: "https://www.dossaniparadise.com",
    websiteDisplay: "www.DossaniParadise.com",
    disclaimer: "",
    assignedDepartments: ["Sales"],
    assignedGroups: ["Leasing"],
    assignedUserIds: [],
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    name: "Spring Leasing Push",
    bannerText: "Now leasing — tour available homes this week →",
    bannerUrl: "https://www.dossaniparadise.com/leasing",
    backgroundColor: "#1F4E79",
    textColor: "#FFFFFF",
    startDate: new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10),
    endDate: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10),
    active: false,
    clicks: 128,
    views: 1820,
    targetDepartments: ["Sales", "Marketing", "Executive"],
  },
];

export function createInitialState(): AppState {
  return {
    users: DEMO_USERS,
    templates: DEMO_TEMPLATES,
    campaigns: DEMO_CAMPAIGNS,
    settings: {
      companyName: "Dossani Paradise Management",
      companyLogo: DEFAULT_LOGO_PATH,
      role: "admin",
      m365Connected: false,
      tenantId: "",
      deployMode: "demo",
      lastSyncAt: new Date().toISOString(),
    },
  };
}
