import type { AppState, Campaign, DirectoryUser, SignatureTemplate } from "./types";

export const DEMO_USERS: DirectoryUser[] = [
  {
    id: "u1",
    displayName: "Catherine Leman",
    email: "catherine.leman@contoso.com",
    jobTitle: "Chief Marketing Officer",
    department: "Executive",
    phone: "+1 (555) 201-4400",
    mobile: "+1 (555) 201-4401",
    company: "Contoso",
    website: "https://contoso.com",
    location: "Seattle, WA",
    linkedIn: "https://linkedin.com/in/catherineleman",
    groups: ["Leadership", "Marketing"],
    signatureId: "t1",
  },
  {
    id: "u2",
    displayName: "Daniel Brooks",
    email: "daniel.brooks@contoso.com",
    jobTitle: "Senior Account Executive",
    department: "Sales",
    phone: "+1 (555) 201-4412",
    company: "Contoso",
    website: "https://contoso.com",
    location: "Austin, TX",
    linkedIn: "https://linkedin.com/in/danielbrooks",
    groups: ["Sales-West"],
    signatureId: "t2",
  },
  {
    id: "u3",
    displayName: "Maya Chen",
    email: "maya.chen@contoso.com",
    jobTitle: "Software Engineer",
    department: "Engineering",
    phone: "+1 (555) 201-4488",
    company: "Contoso",
    website: "https://contoso.com",
    location: "Remote",
    groups: ["Engineering", "Platform"],
    signatureId: "t1",
  },
  {
    id: "u4",
    displayName: "Jordan Blake",
    email: "jordan.blake@contoso.com",
    jobTitle: "Customer Success Lead",
    department: "Support",
    phone: "+1 (555) 201-4490",
    company: "Contoso",
    website: "https://contoso.com",
    location: "Chicago, IL",
    groups: ["Support"],
    signatureId: "t3",
  },
  {
    id: "u5",
    displayName: "Priya Nair",
    email: "priya.nair@contoso.com",
    jobTitle: "Finance Manager",
    department: "Finance",
    phone: "+1 (555) 201-4422",
    company: "Contoso",
    website: "https://contoso.com",
    location: "New York, NY",
    groups: ["Finance"],
    signatureId: "t1",
  },
  {
    id: "u6",
    displayName: "Sam Ortiz",
    email: "sam.ortiz@contoso.com",
    jobTitle: "People Operations",
    department: "HR",
    phone: "+1 (555) 201-4433",
    company: "Contoso",
    website: "https://contoso.com",
    location: "Seattle, WA",
    groups: ["HR"],
    signatureId: "t3",
  },
];

export const DEMO_TEMPLATES: SignatureTemplate[] = [
  {
    id: "t1",
    name: "Corporate Classic",
    description: "Company-wide default with logo, CTA, and disclaimer.",
    layout: "classic",
    primaryColor: "#0F3D3E",
    accentColor: "#E07A3D",
    fontFamily: "Segoe UI, Arial, sans-serif",
    showPhoto: false,
    showLogo: true,
    showSocial: true,
    logoUrl: "",
    logoAlt: "Contoso",
    ctaLabel: "Book a meeting",
    ctaUrl: "https://contoso.com/demo",
    disclaimer:
      "This message and any attachments may contain confidential information intended only for the addressee.",
    assignedDepartments: ["All", "Executive", "Engineering", "Finance", "HR"],
    assignedGroups: [],
    assignedUserIds: [],
    campaignId: "c1",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t2",
    name: "Sales Modern",
    description: "Bold layout for revenue teams with prominent CTA.",
    layout: "modern",
    primaryColor: "#12355B",
    accentColor: "#F4A261",
    fontFamily: "Calibri, Arial, sans-serif",
    showPhoto: true,
    showLogo: true,
    showSocial: true,
    logoUrl: "",
    logoAlt: "Contoso Sales",
    ctaLabel: "Schedule a call",
    ctaUrl: "https://contoso.com/sales",
    disclaimer: "",
    assignedDepartments: ["Sales"],
    assignedGroups: ["Sales-West"],
    assignedUserIds: [],
    campaignId: "c1",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t3",
    name: "Support Compact",
    description: "Compact footer for high-volume support mail.",
    layout: "compact",
    primaryColor: "#1B4332",
    accentColor: "#40916C",
    fontFamily: "Arial, Helvetica, sans-serif",
    showPhoto: false,
    showLogo: false,
    showSocial: false,
    logoUrl: "",
    logoAlt: "Contoso",
    ctaLabel: "Help Center",
    ctaUrl: "https://contoso.com/help",
    disclaimer: "For support SLAs see the Help Center.",
    assignedDepartments: ["Support"],
    assignedGroups: [],
    assignedUserIds: [],
    campaignId: "c2",
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    name: "Spring Product Launch",
    bannerText: "New: Contoso Cloud Suite is live — see what's new →",
    bannerUrl: "https://contoso.com/launch",
    backgroundColor: "#0F3D3E",
    textColor: "#FFFFFF",
    startDate: new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10),
    endDate: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10),
    active: true,
    clicks: 1284,
    views: 18420,
    targetDepartments: ["All", "Sales", "Marketing", "Executive"],
  },
  {
    id: "c2",
    name: "Customer Webinar",
    bannerText: "Join our live webinar: Support excellence at scale",
    bannerUrl: "https://contoso.com/webinar",
    backgroundColor: "#1B4332",
    textColor: "#F8FAF9",
    startDate: new Date(Date.now() - 2 * 86400000).toISOString().slice(0, 10),
    endDate: new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10),
    active: true,
    clicks: 312,
    views: 5400,
    targetDepartments: ["Support", "HR"],
  },
];

export function createInitialState(): AppState {
  return {
    users: DEMO_USERS,
    templates: DEMO_TEMPLATES,
    campaigns: DEMO_CAMPAIGNS,
    settings: {
      companyName: "Contoso",
      companyLogo: "",
      role: "admin",
      m365Connected: false,
      tenantId: "",
      deployMode: "demo",
      lastSyncAt: new Date().toISOString(),
    },
  };
}
