import { DEFAULT_LOGO_PATH, DOSSANI_DISCLAIMER } from "./constants";
import type { AppState, Campaign, DirectoryUser, SignatureTemplate } from "./types";

/** Placeholder recipient used only by server HTML preview helpers. */
export const PREVIEW_USER: DirectoryUser = {
  id: "preview",
  displayName: "Team Member",
  email: "team@dossaniparadise.com",
  jobTitle: "Title",
  department: "Operations",
  phone: "",
  company: "Dossani Paradise Management",
  website: "https://www.dossaniparadise.com",
  streetAddress: "",
  cityStateZip: "",
  location: "",
  groups: [],
  signatureId: "t-dossani",
  source: "findmi",
};

export const DEMO_TEMPLATES: SignatureTemplate[] = [
  {
    id: "t-dossani",
    name: "Dossani Paradise Corporate",
    description:
      "Company-wide signature with logo, FindMi-style address fields, and legal disclaimer.",
    layout: "corporate",
    primaryColor: "#1F4E79",
    accentColor: "#C0392B",
    fontFamily: "Georgia, 'Times New Roman', Times, serif",
    fontSize: 12,
    showPhoto: false,
    showLogo: true,
    showSocial: false,
    showThankYou: true,
    logoUrl: DEFAULT_LOGO_PATH,
    logoAlt: "Dossani Paradise Management",
    logoWidth: 96,
    companyNameLine1: "Dossani Paradise",
    companyNameLine2: "Management",
    companyNameLine2Color: "#C0392B",
    ctaLabel: "",
    ctaUrl: "",
    websiteDisplay: "www.DossaniParadise.com",
    disclaimer: DOSSANI_DISCLAIMER,
    assignedDepartments: ["All"],
    assignedGroups: [],
    assignedUserIds: [],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t2",
    name: "Sales Modern",
    description: "Alternate layout for leasing / sales outreach.",
    layout: "modern",
    primaryColor: "#1F4E79",
    accentColor: "#C0392B",
    fontFamily: "Calibri, Arial, Helvetica, sans-serif",
    fontSize: 12,
    showPhoto: true,
    showLogo: true,
    showSocial: false,
    showThankYou: false,
    logoUrl: DEFAULT_LOGO_PATH,
    logoAlt: "Dossani Paradise Management",
    logoWidth: 80,
    companyNameLine1: "Dossani Paradise",
    companyNameLine2: "Management",
    companyNameLine2Color: "#C0392B",
    ctaLabel: "Schedule a tour",
    ctaUrl: "https://www.dossaniparadise.com",
    websiteDisplay: "www.DossaniParadise.com",
    disclaimer: "",
    assignedDepartments: ["Operations"],
    assignedGroups: ["Leasing"],
    assignedUserIds: [],
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    name: "Spring Leasing Push",
    bannerText: "Now leasing — tour available homes this week →",
    bannerUrl: "https://www.dossaniparadise.com/leasing",
    backgroundColor: "#1F4E79",
    textColor: "#FFFFFF",
    startDate: new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10),
    endDate: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10),
    active: false,
    clicks: 128,
    views: 1820,
    targetDepartments: ["Operations", "Marketing", "Executive"],
  },
];

export function createInitialState(): AppState {
  return {
    users: [],
    stores: [],
    findMiOverrides: {},
    templates: DEMO_TEMPLATES,
    campaigns: DEMO_CAMPAIGNS,
    settings: {
      companyName: "Dossani Paradise Management",
      companyLogo: DEFAULT_LOGO_PATH,
      role: "admin",
      m365Connected: false,
      findMiConnected: false,
      tenantId: "",
      azureClientId: "",
      azureOrgDomain: "",
      exchangeAppConsented: false,
      exchangeRbacAssigned: false,
      deployMode: "demo",
      lastSyncAt: new Date().toISOString(),
    },
  };
}
